In [ ]:
import tensorflow as tf
import numpy as np

In [2]:
model = tf.keras.models.load_model('model.h5')

In [6]:
img = tf.keras.utils.load_img("cast_ok_0_196.jpeg")
img = tf.keras.utils.img_to_array(img)
img = tf.image.resize(img, [224, 224])
img = tf.expand_dims(img, axis=0)
print(img)
np.round(model.predict(img))

tf.Tensor(
[[[[143.07143 143.07143 143.07143]
   [140.92857 140.92857 140.92857]
   [137.42857 137.42857 137.42857]
   ...
   [154.21426 154.21426 154.21426]
   [147.14288 147.14288 147.14288]
   [150.64282 150.64282 150.64282]]

  [[143.07143 143.07143 143.07143]
   [140.92857 140.92857 140.92857]
   [137.42857 137.42857 137.42857]
   ...
   [154.21426 154.21426 154.21426]
   [147.14288 147.14288 147.14288]
   [150.64282 150.64282 150.64282]]

  [[143.07143 143.07143 143.07143]
   [140.92857 140.92857 140.92857]
   [137.42857 137.42857 137.42857]
   ...
   [154.21426 154.21426 154.21426]
   [147.14288 147.14288 147.14288]
   [150.64282 150.64282 150.64282]]

  ...

  [[166.07143 166.07143 166.07143]
   [166.78572 166.78572 166.78572]
   [168.42857 168.42857 168.42857]
   ...
   [174.21426 174.21426 174.21426]
   [176.21432 176.21432 176.21432]
   [171.49976 171.49976 171.49976]]

  [[166.07143 166.07143 166.07143]
   [166.78572 166.78572 166.78572]
   [168.42857 168.42857 168.42857]
 

array([[0.]], dtype=float32)